In [3]:
import os
import numpy as np
import pandas as pd


In [2]:
s = r'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
print('URL:', s)

df = pd.read_csv(s, header=None, encoding='utf-8')
print(df.tail())

URL: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data
       0    1    2    3               4
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica


In [4]:
X = df.iloc[0:100, [0, 2]].values
s = np.random.random_sample(X.shape[0])
print(X[0:10])
print(s[0:10])

[[5.1 1.4]
 [4.9 1.4]
 [4.7 1.3]
 [4.6 1.5]
 [5.  1.4]
 [5.4 1.7]
 [4.6 1.4]
 [5.  1.5]
 [4.4 1.4]
 [4.9 1.5]]
[0.32003709 0.57874493 0.33745093 0.30497208 0.28407497 0.67702618
 0.28682451 0.09229911 0.15573585 0.18697316]


In [5]:
print(X.shape)
print(s.shape)

(100, 2)
(100,)


In [6]:
print(np.dot(X.T, s))

[278.91131405 148.19666345]


In [7]:
dd = np.dot(X[:,0],s)
print(dd)

278.91131404703543


In [8]:
print(X.shape[1])

2


In [10]:
s_ = np.random.random_sample(X.shape)
print(s_[0:10])
print(s_.shape)

[[0.94516179 0.68744246]
 [0.23920295 0.23332407]
 [0.38788094 0.5162145 ]
 [0.79616984 0.03049534]
 [0.0913209  0.91845948]
 [0.70367023 0.91687048]
 [0.51267339 0.48625392]
 [0.66840477 0.42930328]
 [0.28223618 0.39000376]
 [0.78681876 0.06467354]]
(100, 2)


In [11]:
dd = np.dot(X[:,0],s_)
print(dd)

[276.95012932 275.68219364]


In [12]:
print(X.T)

[[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
  5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
  5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
  6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
  6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
  5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7]
 [1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 1.5 1.6 1.4 1.1 1.2 1.5 1.3 1.4
  1.7 1.5 1.7 1.5 1.  1.7 1.9 1.6 1.6 1.5 1.4 1.6 1.6 1.5 1.5 1.4 1.5 1.2
  1.3 1.5 1.3 1.5 1.3 1.3 1.3 1.6 1.9 1.4 1.6 1.4 1.5 1.4 4.7 4.5 4.9 4.
  4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 4.4 4.5 4.1 4.5 3.9 4.8 4.
  4.9 4.7 4.3 4.4 4.8 5.  4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.
  4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 3.  4.1]]


In [13]:
# w_は(100, 2)
# Xは(100, 2)
print(X.T.dot(w_))  # (2,100)と(100,2)のドット積
print(np.dot(X.T,s_))  # 同上
print(np.dot(X.T,s_).shape)  # (2, 2)
print("---")
print(np.dot(s_,X.T))  # (100,2)と(2,100)のドット積
print(np.dot(s_,X.T).shape)  # (100, 100)

[[252.64450696 274.30588802]
 [134.70975313 139.82493788]]
[[276.95012932 275.68219364]
 [144.29000636 139.31754816]]
(2, 2)
---
[[5.78274457 5.59371222 5.33593561 ... 8.81600568 6.88265251 8.2059363 ]
 [1.54658877 1.49874818 1.42757518 ... 2.48635183 1.91990728 2.32008554]
 [2.7008931  2.62331691 2.49411927 ... 4.62458419 3.5268363  4.32740082]
 ...
 [2.22371078 2.18566947 2.0580812  ... 5.02979959 3.65646201 4.75560241]
 [5.41437652 5.24274924 4.99698761 ... 8.50822257 6.60052604 7.93088568]
 [2.75242739 2.69131103 2.5449118  ... 5.56177079 4.11695342 5.23841414]]
(100, 100)


In [14]:
print(np.dot(X,s_))  # (100,2)と(100,2)のドット積
# 怒られる

ValueError: shapes (100,2) and (100,2) not aligned: 2 (dim 1) != 100 (dim 0)

In [6]:
a=np.clip(-550,-250,250)
print(a)

-250
